### ISSUE TITLE
Bug: Mux reset Method should set the MUX to a clear state

### ISSUE THREAD

**Issue by CytheY** [varj888/amos-ss17-projSivantos#115]
Mux reset Method currently sets the standard "TestFamily" "TestModel" instead of just reseting the MUX

**Comment by Tango1266** [comment]
do we neet the method for the final version?

**Comment by CytheY** [comment]
Good question for the POs ;)

**Comment by Tango1266** [comment]
well, it was not backlog item and we used it for debugging. But yeah, we cant know for sure whether they need it or not
