### ISSUE TITLE
Bug: Button Press Duration in Frontend

### ISSUE THREAD

**Issue by CytheY** [varj888/amos-ss17-projSivantos#116]
Button Press Duration should be hardcoded in the backend

**Comment by Tango1266** [comment]
Does it reference to that the duration should be handled in backend?

**Comment by CytheY** [comment]
Yes the duration should be handled in the backend. 
Short : 200ms
Medium: 1500ms
Long: 3000ms

**Comment by Tango1266** [comment]
This was debugged and is ready for testing in "debugging" branch
