### ISSUE TITLE
[BUG] Enable only one Volume Control

### ISSUE THREAD

**Issue by adrianmkofficial** [varj888/amos-ss17-projSivantos#121]
BUG: Currently both Endless & Sliding Volume Control are always enabled in UI.
FIX: Only keep appropriate one enabled.

Story ID: 40

**Comment by varj888** [comment]
not sure if I completely understand the issue. More details, please

**Comment by Tango1266** [comment]
Hi Models have either Endless Volume Control or Analog Volume Control, not both. So e.g. if the x pin config has a Endless Volume Controll then Analog Volume Control should be deactivated and wise versa.
