### ISSUE TITLE
[BUG] RemoteControllerTitleBarView not updating Title

### ISSUE THREAD

**Issue by adrianmkofficial** [varj888/amos-ss17-projSivantos#126]
BUG: The Title in RemoteControllerTitleBarView is not updating to the appropriate, current model selected on the Raspberry Pi.

Story ID: 40

**Comment by varj888** [comment]
ich habe es fast fertig (arbeite am branch bugFixingV1). Brauche nur Info über wo genau info über letzt benutzes HI gespeichert wird (Model und Family)

**Comment by Tango1266** [comment]
die daten werden auf dem Raspberry Pi gespeichert und müssen vom Frontend angefordert werden. Es gibt bereits eine Operation "GetRaspiConfiguration" die alle configuration informationen holt. Da könnte man sich die infos rausholen.

**Comment by varj888** [comment]
Danke!
implemented in bugFixingV1 branch
