### ISSUE TITLE
[GUI] We need a debug tab in the new GUI

### ISSUE THREAD

**Issue by Tango1266** [varj888/amos-ss17-projSivantos#133]
* We need the following debug functionality:
** Read, Write, Reset Gpio Pins
** Set x y values of Multiplexer

**Comment by varj888** [comment]
ready except the ResetMux command throws an Exception: "Specified cast is not valid".

**Comment by varj888** [comment]
It was because of async Task<bool>  in RaspberryPi class while ResetMux Operation hast return type string.  Changed to async Task<string> ResetMux().

**Comment by varj888** [comment]
implemented in bugFixingV1 branch
