### ISSUE TITLE
[Networking/Gui] Disconnection Backend-Testmachine

### ISSUE THREAD

**Issue by Tango1266** [varj888/amos-ss17-projSivantos#145]
A Backend which looses Connection should disapear in the Frontend

**Comment by varj888** [comment]
I don't really understand this description. More details, please:)

**Comment by Tango1266** [comment]
If a Fronten is connected with a Backend, then it appears in the Raspberry Pi Connection list. But when the Backend somehow looses connection, then it should dissapear. For now, it is still their like it is still connected.
