### ISSUE TITLE
76) As a user, I want to have a registry server, where rasperry pis can register with their ip-address

### ISSUE THREAD

**Issue by Tango1266** [varj888/amos-ss17-projSivantos#45]
- A visuell feedback shall be presented that the registry server finds one Raspberry Pi in the same network

**Comment by CytheY** [comment]
Hey Marco,

wie ist der Registry Server gedacht? Laufen die Requests nun alle über den Registry Server?
Oder verbindet der Registry Sever nur das Frontend mit dem entsprechenden Raspberry?
